python cnas.py --resume ../results/nachos-cifar10/iter_0 --sec_obj avg_macs \
              --n_gpus 1 --gpu 1 --n_workers 4 \
              --data ../datasets/cifar10 --dataset cifar10 --n_classes 10\
              --first_predictor as --sec_predictor as \
              --supernet_path ./supernets/ofa_mbv3_d234_e346_k357_w1.0 --pretrained  \
              --save ../results/nachos-cifar10 --iterations 2 \
              --search_space eemobilenetv3 --trainer_type multi_exits --method joint \
              --n_epochs 3 --val_split 0.1 \
              --warmup_ee_epochs 2 --ee_epochs 0 \
              --mmax 5 --top1min 0.65 \
              --lr 32 --ur 32 