name: bernulli
beta: 1
joint_type: logits
sample: false
pre_trained: true
regularization_loss: bce
prior_mode: ones
fix_last_layer: true
normalize_weights: true
regularization_scaling: false
temperature_scaling: true
dropout: 0
backbone_epochs: 0
global_gate: False
w_alpha: 1.0
w_beta: 1.0
w_gamma: 1.0
n_epoch_gamma: 10
checkpoint: True